### Obtener todos los detalles de venta
GET http://localhost:8002/ventas/detalle
Content-Type: application/json

###

### Obtener un detalle de venta por ID
GET http://localhost:8002/ventas/detalle/6
Content-Type: application/json

###

### Crear un nuevo detalle de venta
POST http://localhost:8002/ventas/detalle
Content-Type: application/json

{
    "id_venta": 1,
    "id_producto": 5,
    "cantidad": 2
}

### Actualizar un detalle de venta
PUT http://localhost:8002/ventas/detalle/6
Content-Type: application/json

{
    "id_producto": 6,
    "cantidad": 2
}

### Obtener todos los detalles de venta de una venta
GET http://localhost:8002/ventas/detalle/venta/1
Content-Type: application/json


### Eliminar un detalle de venta
DELETE http://localhost:8002/ventas/detalle/6
Content-Type: application/json
